{% set name = "neurodsp" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neurodsp-tools/neurodsp/archive/{{ version }}.tar.gz
  sha256: 27c9f8e5f0cf51ba6904be29d7934b46819d9f8d243307348aff960766101aa1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - neurodsp
    - neurodsp.aperiodic
    - neurodsp.burst
    - neurodsp.filt
    - neurodsp.plts
    - neurodsp.rhythm
    - neurodsp.sim
    - neurodsp.spectral
    - neurodsp.tests
    - neurodsp.timefrequency
    - neurodsp.utils
  commands:
    - pip check
    - python -c "import neurodsp; assert neurodsp.__version == '{{ version }}', neurodsp.__version"

about:
  home: https://github.com/neurodsp-tools/neurodsp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Digital signal processing for neural time series.
  doc_url: https://neurodsp-tools.github.io/neurodsp/
  dev_url: https://github.com/neurodsp-tools/neurodsp

extra:
  recipe-maintainers:
    - ryanhammonds
    - larsoner
