{% set name = "neurodsp" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ec713c3dda5bc3af7facf5b81ee5374fe520b131e71cc16e66f02834a07ff7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - neurodsp
    - neurodsp.burst
    - neurodsp.filt
    - neurodsp.plts
    - neurodsp.rhythm
    - neurodsp.sim
    - neurodsp.spectral
    - neurodsp.tests
    - neurodsp.timefrequency
    - neurodsp.utils
  requires:
    - pytest

about:
  home: https://github.com/neurodsp-tools/neurodsp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Digital signal processing for neural time series.
  doc_url: https://neurodsp-tools.github.io/neurodsp/
  dev_url: https://github.com/neurodsp-tools/neurodsp

extra:
  recipe-maintainers:
    - ryanhammonds
