{% set name = "neurodsp" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neurodsp-tools/neurodsp/archive/{{ version }}.tar.gz
  sha256: 1357f79076d4002755abd22a3e72494bf4b298bf528361420b2ef3788ad8ecf6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - neurodsp
    - neurodsp.aperiodic
    - neurodsp.burst
    - neurodsp.filt
    - neurodsp.plts
    - neurodsp.rhythm
    - neurodsp.sim
    - neurodsp.spectral
    - neurodsp.tests
    - neurodsp.timefrequency
    - neurodsp.utils

about:
  home: https://github.com/neurodsp-tools/neurodsp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Digital signal processing for neural time series.
  doc_url: https://neurodsp-tools.github.io/neurodsp/
  dev_url: https://github.com/neurodsp-tools/neurodsp

extra:
  recipe-maintainers:
    - ryanhammonds
