{% set name = "neurodsp" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neurodsp-tools/neurodsp/archive/{{ version }}.tar.gz
  sha256: acdfef6d990f16bd488e11e36d05f58f282079f6c4f17e40f85a0ac5f5713805

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - neurodsp
    - neurodsp.aperiodic
    - neurodsp.burst
    - neurodsp.filt
    - neurodsp.plts
    - neurodsp.rhythm
    - neurodsp.sim
    - neurodsp.spectral
    - neurodsp.tests
    - neurodsp.timefrequency
    - neurodsp.utils

about:
  home: https://github.com/neurodsp-tools/neurodsp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Digital signal processing for neural time series.
  doc_url: https://neurodsp-tools.github.io/neurodsp/
  dev_url: https://github.com/neurodsp-tools/neurodsp

extra:
  recipe-maintainers:
    - ryanhammonds
